DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "ride_bids" CASCADE;
DROP TABLE IF EXISTS "riders" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "__drizzle_migrations" CASCADE;
